kind: "DeploymentConfig"
apiVersion: "apps.openshift.io/v1"
metadata:
  name: "test-deployment"
  namespace: "test-deployment"
spec:
  template:
    metadata:
      labels:
        name: "test-deployment"
        namespace: "test-deployment"
    spec:
      containers:
        - name: "test-deployment"
          image: "alex-ecc/test-deployment"
          ports:
            - containerPort: 8400
              protocol: "TCP"
  replicas: 1
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "alex-ecc/test-deployment"
        from:
          kind: "ImageStreamTag"
          name: "test-deployment:latest"
  strategy:
    type: "Rolling"
  paused: false
  revisionHistoryLimit: 2
